### ISSUE TITLE
Forbidden 403 on artylab.expedia.biz

### ISSUE THREAD

**Issue by TaufanP** [Abouelyatim/React-App-Clean-Architecture#2]
When I ran `npm install`, it produced an error:

`403 Forbidden - GET https://artylab.expedia.biz/api/npm/public-npm-virtual/yocto-queue/-/yocto-queue-0.1.0.tgz`

How can I fix this?

**Comment by TaufanP** [comment]
~~Deleting the  `yarn.lock` and run `yarn` solved it.~~

Omg, wrong repository, sorry!

Issue still exists.

**Comment by Abouelyatim** [comment]
Issue fixed, pls check
I forgot to remove my private registry

**Comment by TaufanP** [comment]
It works thank you!
